### ISSUE TITLE
Feature: User Profile Page

### ISSUE THREAD

**Issue by danieloh99** [cs130-w21/10#1]
## Epic
As a user, I want to be able to make a profile.
## User Stories
- [x] As a user, I want to show my areas of expertise and areas of interest to other users. #36 
- [x] As a user, I want to specify my contact information on my profile so that other users can contact me. #36 
- [x] As a user, I want to edit the information on my profile at any time after creating my account #62 
## List of Tasks
- [x] Design profile page and decide on details: bio, areas of expertise, areas of interest, contact info
- [x] Decide on default information to be displayed or allow users to choose which information to be displayed on user card
- [x] Set up database to store profile details
- [x] Implement design
- [x] Add Edit profile action to edit profile information
- [x] Add navigation to other pages as necessary
