### ISSUE TITLE
MatchPage Single Match Popup

### ISSUE THREAD

**Issue by jordanXYsoon1998** [cs130-w21/10#15]
## User Story
As a **user**, I would like **to click on a single match and view their profile/contact information** so that **I can understand them better before proceeding to contact them**.

## Detailed Description
A user will be able to click on the individual match in the MatchList Page #6 to view their profile with contact information included.

## Tasks
- [x] Create and render template for each individual match's summarized profile details #10
- [x] Add logic to so this popup appears when a user is clicked in the [full matches page](https://github.com/cs130-w21/10/issues/29) #35 

## Acceptance Criteria
- [x] Given **that the user can view all matches and clicks a single match**, then **a profile summary popup for that corresponding match will be shown**.
