### ISSUE TITLE
Feature: User Swipe Page

### ISSUE THREAD

**Issue by Jwang20217** [cs130-w21/10#2]
## Epic
As a user I want to swipe / like the people I want to connect with

## User Stories
- As a user, I want to see the profile cards of those with experience in specific areas of interest
- As a user, I want to either like or decline a profile 
- As a user, I want to see if I got a match if those who I like also like me back and be able to connect with them
- As a user, I want the information displayed to be clear and concise
- As a user, I want to be able to see who likes me. 
## List of Tasks
- [x] First display cards of people who have liked the user
- [x] Then display profile cards for user based on profiles stored in database who the user has not swiped on and who matches the interest of the user
- [x] Keep track of list of users current user has swiped on and has liked
- [x] Implement design and layout of a profile card
- [x] Implement like / swipe feature
- [x] If user likes a profile card check to see if the other user liked them back
- [x] If there is a match, display "a match prompt" on the screen and enable exchange of contact information (redirect to user messaging page if we implement that stretch goal) with match
