### ISSUE TITLE
User Swipe Page: View Profile Cards

### ISSUE THREAD

**Issue by Jwang20217** [cs130-w21/10#22]
## User Story
As a **User**, I would like **to see profile cards** so that **I can swipe on them**.

## Detailed Description
I need to create profile pages so the user can swipe on them 

## Tasks 
- [x] Create Profile Page Cards #24 
- [x] Display Different Users Information From Database onto card #27

## Acceptance Criteria
- [x] Given **User Swipe Page Render**, then **View Profile Cards for Different Users that they can swipe on**
