### ISSUE TITLE
Access Protection + User Creation

### ISSUE THREAD

**Issue by danieloh99** [cs130-w21/10#23]
## User Story
As a user, I want to make sure no one can access my profile except myself.

## Detailed Description
We need to add routing to the different pages that is protected by authentication. Users should only be able to see their own accounts. 

When a user signs up, a new User object should be created and linked to their account/email. The user should also be redirected to the Profile Page with the Edit Profile component open.
When a user signs in, their User object should be used to fill in details on the other pages. They should be redirected to the swiping page.
If a user tries to go to a page without having logged in, they should be redirected to the login page.

## Acceptance Criteria
- [x] Given successful SIGNUP, then create a new user object linked to a user's account. Redirect to profile page, with edit component open. #21 #25
- [x] Given successful LOGIN, then get corresponding user object. Redirect to swiping page (dependent on swiping page). #26 #28
- [x] Given attempt to access any page other than login without logging in, then redirect to login page. #13
