### ISSUE TITLE
Swipe Functionality 

### ISSUE THREAD

**Issue by Jwang20217** [cs130-w21/10#30]
## User Story
As a **User**, I would like **to swipe on profile cards** so that **I can either like or dislike a user**.

## Detailed Description
I want to be able to swipe right on users which I like and want to match on and right on users I dislike

## Tasks
- [x] Implement swiping function (L/R) and up or down disabled #31 
- [x] On swipe right check if match with user #33
- [x] Based on swipe direction input in database if given user likes profile of user they swiped on #32

## Acceptance Criteria
- [x] Given **Swipe Right**, then **If user also likes me there is a match**
- [x] Given **Swipe Left**, then **I dislike user**
