### ISSUE TITLE
Profile Page Show Info

### ISSUE THREAD

**Issue by ElwynCruz** [cs130-w21/10#36]
## User Story
As a user, I want to show my personal information on my profile page.

## Detailed Description
Create a profile page that allows users to show their areas of expertise, what they are interested in, contact information to others.

## Tasks
- [x] Design profile page #38 
- [x] Load user info using user ID from database #39 
- [x] Only allow access to this page after successful login

## Acceptance Criteria
- [x] Given **a user is logged in**, then **their profile should display their profile information.**
