### ISSUE TITLE
Profile Page: Customize Card Information (Stretch Goal)

### ISSUE THREAD

**Issue by ElwynCruz** [cs130-w21/10#37]
## User Story
As a user, I want to specify which information should be displayed on my card for other people who are swiping.

## Detailed Description
Allow users to customize their own cards that other users see by showing/hiding information of their choice.

## Tasks
- [ ] Create a card preview so users can see their changes in real time
- [ ] Create form to accept user edits
- [ ] Save user changes to database on submit
## Acceptance Criteria
- [ ] Given **user makes changes to their card**, then **their edits are shown in their card preview**.
- [ ] Given **user submits changes to their card**, then **their edits are saved and shown when other users view their card**.

**Comment by jordanXYsoon1998** [comment]
Turned into a stretch goal that we decided not to implement due to time constraints.
