### ISSUE TITLE
Feature: User Register Page

### ISSUE THREAD

**Issue by Jwang20217** [cs130-w21/10#4]
## Epic
As a user, I want to register for an account on the app

## User Stories
- As a user I want to input my email and create a new username and password for my username 
- As a user I want to be redirected to the app when I have registered
- As a user I want the process to be concise so I can start connecting faster.
- As a user I want the process to be easy to understand.

## List of Tasks
- [x] Store all username / password mappings in database (username can be email)
- [x] When a user submits registration check if username is already taken, if so output error
- [x] If username is not taken store username / password mapping in database and create a new entry for user in database with username as their key
- [x] Implement hashing function so that password is not visible to us
- [x] Upon successful registration redirect user to profile page of app
- [x] Create a password strength bar to indicate password strength 
- [x] (Optional) Register through google account
