### ISSUE TITLE
Full Matches Page View/Render 2

### ISSUE THREAD

**Issue by knguyen99** [cs130-w21/10#48]
## User Story
As a **[User]**, I would like **[to be able to access the match page easily]** so that **[i can see my matches]**.

## Detailed Description
Connect matches page  to navbar, begin rendering users

## Tasks
- [x] Connect match page to navbar #49 
- [x] Get user id info #50
- [x] display cards of information summary of matches #51

## Acceptance Criteria
- [x] Given **[ the user has matches]**, then **[the user should see details on matches]**
