### ISSUE TITLE
Feature: User Messaging Page (Stretch Goal)

### ISSUE THREAD

**Issue by Jwang20217** [cs130-w21/10#5]
## Epic
As a user, I want to message the people I have matched with

## User Stories
- As a user, I want to send and receive messages
- As a user, I want to see all the people I have matched with 
- As a user, I want to click on a person I have matched with to start or view our conversation 
- As a user, I want to be able to delete messages

## List of Tasks
- [ ] Store all messages sent between two users in a database
- [ ] When a user sends a message then update the chat messages in the database to include new message
- [ ] Implement design / display of chat screen with messages between two users
- [ ] Implement design / display of main chat page where user can click on a match to view conversation 
- [ ] Implement redirect from clicking on specific person in main chat page to their specific chat box

**Comment by jordanXYsoon1998** [comment]
Due to time constraints, we won't be implementing this feature. From the beginning, we did label it as a stretch goal and it was a good thing we did!
