### ISSUE TITLE
All Match Page

### ISSUE THREAD

**Issue by knguyen99** [cs130-w21/10#57]
## User Story
As a **[User]**, I would like **[View all matches]** so that **[I can see who I matched with and contact them]**.

## Detailed Description
A user should be able to view all of the users they have matched with. With the list of all of their matches, a match card should be generated with the corresponding profile and summarized information. At the bottom of each match card should be a button that opens a popup with detailed information on that profile. 

## Tasks
- [x] Set up click to open Single Match popup #58 
- [x] Start working on UI for Match page and match with rest of site #59
- [x] Get current user id when logged in #60

## Acceptance Criteria
- [x] Given **[the user is logged in]**, then **[the correct matches page is shown]**
- [x] Given **[the user is clicks on a match]**, then **[the expected match popup is shown]**
