### ISSUE TITLE
Feature: User Match Page

### ISSUE THREAD

**Issue by jordanXYsoon1998** [cs130-w21/10#6]
## Epic
Description: The user can view a list of everyone they've matched with.

## User Stories
- [x] As a user, I want to see the entire list of people I've matched with. #29 
- [x] As a user, I want to click on a single match and view their profile/contact information. #15 

## List of Tasks
- [x] Render list layout on the front end
- [x] Add logic to back-end to return a list of all matches.
- [x] Return URLs to profile/contact info/messaging

**Comment by jordanXYsoon1998** [comment]
Redefined the epic due to time constraints. Got rid of the messaging matches link and turned it to a [stretch goal](https://github.com/cs130-w21/10/issues/5).
