### ISSUE TITLE
ProfilePage Edit Info Popup

### ISSUE THREAD

**Issue by jordanXYsoon1998** [cs130-w21/10#62]
## User Story
As a **user**, I would like **to edit the information on my profile at any time** so that **I can enter my details for the first time after creating my account or update my details upon any changes to career, experience etc**.

## Detailed Description
A user will be able to click on an edit button on their profile page to open an edit popup. This popup will contain the form fields to make changes to their personal details/contact information etc. The user will be able to view any existing information the profile already has, make changes to them, and save the changes to the database.

## Tasks
- [x] Create and render basic skeleton form template for each individual user profile's edit popup. #63 
- [x] Add connection between the form and database to save any changes. #64 
- [x] Add logic so this popup appears when the edit button in the [user's profile page](https://github.com/cs130-w21/10/issues/1) is clicked. #65 

## Acceptance Criteria
- [x] Given **that the user can view their own profile page and clicks on the edit button**, then **a edit profile popup for that user will be shown**.
- [x] Given **that the edit profile popup has appeared**, the user can view their profile's existing information in the populated form.
- [x] Given **that the edit profile popup has appeared**, the user can make changes to their profile's information on the form.
- [x] Given **that the edit profile popup has appeared and changes were made**, the user can save the changes to the database.

**Comment by jordanXYsoon1998** [comment]
Pull Request #66 closed this issue
