### ISSUE TITLE
Redirect To Edit Profile if they don't have a completed profile

### ISSUE THREAD

**Issue by danieloh99** [cs130-w21/10#69]
## User Story
As a user, I would like to have a completed profile before using the application so that people can swipe my profile.

## Detailed Description
Right now, users might create a profile and then navigate somewhere else. If they do, there could be problems since they're expected to have a finished profile. For every protected page, we will check if they have a finished profile, and if they don't we will redirect them to some page where they can complete their profile. For now this will be the edit profile portion of the Profile page, but this may change later, so we will separate out the Edit Profile component.

For a complete profile, the user must have filled out their Name, at least 1 area of interest, at least 1 expertise. These requirements may change later.

## Tasks
- [x] Separate the edit profile into another component so that it could belong to a popup or a page etc. #74
- [x] Update the edit profile to alert a redirected user so they understand why they're getting redirected. #75
- [x] Check for completed profile for protected routes, and redirect to edit profile component if incomplete. #76

## Acceptance Criteria
- [x] Given user is logged in and completed profile, then direct them to the specified page
- [x] Given user is logged in and not completed profile, then direct them to the edit profile component.
- [x] Given user got redirected to edit profile component, then inform them through a message/alert why they got redirected.

**Comment by jordanXYsoon1998** [comment]
All done woot woot
