### ISSUE TITLE
Edit Profile Page: Allow More Education/Work Info

### ISSUE THREAD

**Issue by jordanXYsoon1998** [cs130-w21/10#70]
## User Story
As a **user**, I would like **to be able to add more info to education and work rather than just a single string** so that **I can display more information**.

## Detailed Description
The user will be able to add fields under education like 'major', 'school', 'graduationYear' etc, as well as fields under work like 'company', 'position' etc, as well as a 'bio' field.
By adding these sub-fields, it allows the user to structure their data. It also allows developers to write code to take advantage of this structuring to present the info in more dynamic ways rather than just present a single string.

## Tasks
- [x] Add more sub-fields to the EditProfile component for work and education #71 
- [x] Change save to DB code so that it saves these sub-fields as an object under `education` and `work`. #72

## Acceptance Criteria
- [x] Given **that the user can access the edit profile page/popup**, then **they can view/edit their sub-fields and save any changes to the database**.
