### ISSUE TITLE
UI Design of Entire Site

### ISSUE THREAD

**Issue by knguyen99** [cs130-w21/10#78]
## User Story
As a **[User]**, I would like **[the design to look cohesive]** so that **[it looks better]**.

## Detailed Description
- [x] Update UI for Match page #79 
- [x] Update UI for NavBar #80
- [x] Update UI for main page #81

## Acceptance Criteria
- [x] Given **[Navigates different pages]**, then **[the page design looks similar]**
