### ISSUE TITLE
User Swipe Page: Filter Profile Cards Deck Display

### ISSUE THREAD

**Issue by Jwang20217** [cs130-w21/10#85]
## User Story
As a **User**, I would like **To See a Filtered Profile Deck** so that **I can have an easier time finding new people to connect with who have similar interests**.

## Detailed Description
Modify the Profile Cards Deck which are rendered to filter out user profiles whom they have already Swiped On. Filter the users with similar interests to show at the beginning of the deck for a user to swipe on. 

## Tasks
- [x] FIlter Users With Similar Interests First #83 
- [x] Filter out users in dontSwipe and like array #84 

## Acceptance Criteria
- [x] Given **Already Swipe On User**, then **User is not in Profile Cards Deck to Swipe On**
- [x] Given **Have Similar Interests with User**, then **They are at the front of the deck **
